DanEnrriquez17/our-care-team

db/seeds.rb
created a seed file with
* an admin user
* family members
* caretakers
* a team
=> created some seeds for team and users

app/controllers/event_invited_user_controller.rb, app/controllers/events_controller.rb, app/models/event.rb, app/views/event_invited_user/create.html.erb, app/views/event_invited_user/destroy.html.erb, app/views/event_invited_user/edit.html.erb, app/views/event_invited_user/index.html.erb, app/views/event_invited_user/new.html.erb, app/views/event_invited_user/show.html.erb, app/views/event_invited_user/update.html.erb, app/views/events/create.html.erb, app/views/events/destroy.html.erb, app/views/events/edit.html.erb, app/views/events/index.html.erb, app/views/events/new.html.erb, app/views/events/show.html.erb, app/views/events/update.html.erb, config/routes.rb, test/controllers/event_controller_test.rb, test/controllers/event_invited_user_controller_test.rb
created event controller but am still testing out with the views.  It mostly works but more work needs to be done
=> Event controller branch

Gemfile, Gemfile.lock, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/index_page.scss, app/controllers/post_mentioned_users_controller.rb, app/controllers/posts_controller.rb, app/helpers/application_helper.rb, app/models/post.rb, app/views/post_mentioned_users/create.html.erb, app/views/post_mentioned_users/index.html.erb, app/views/post_mentioned_users/new.html.erb, app/views/posts/_post_form.html.erb, app/views/posts/edit.html.erb, app/views/posts/index.html.erb, app/views/posts/new.html.erb, app/views/posts/show.html.erb, config/environments/development.rb, config/routes.rb, config/storage.yml, db/migrate/20230613224936_create_active_storage_tables.active_storage.rb, db/schema.rb, db/seeds.rb, test/controllers/post_mentioned_users_controller_test.rb
Post controller ready
Post mentioned users controller ready
Associations between the 2 tables checked
Cloudinary installed
Some style to the index page added
=> Post branch

Gemfile.lock, app/controllers/tasks_assigned_users_controller.rb, app/controllers/tasks_controller.rb, app/models/task.rb, app/views/tasks/create.html.erb, app/views/tasks/destroy.html.erb, app/views/tasks/edit.html.erb, app/views/tasks/index.html.erb, app/views/tasks/new.html.erb, app/views/tasks/show.html.erb, app/views/tasks/update.html.erb, app/views/tasks_assigned_users/create.html.erb, app/views/tasks_assigned_users/destroy.html.erb, app/views/tasks_assigned_users/edit.html.erb, app/views/tasks_assigned_users/index.html.erb, app/views/tasks_assigned_users/new.html.erb, app/views/tasks_assigned_users/show.html.erb, app/views/tasks_assigned_users/update.html.erb, config/routes.rb, db/migrate/20230613201353_rename_type_in_tasks_model.rb, db/schema.rb, db/seeds.rb, test/controllers/tasks_assigned_users_controller_test.rb, test/controllers/tasks_controller_test.rb
added tasks controller and views
=> June13 isaacsession

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/home_index_page.scss, app/controllers/users_controller.rb, app/views/events/index.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/posts/index.html.erb, app/views/shared/_navbar.html.erb, app/views/tasks/index.html.erb, app/views/users/create.html.erb, app/views/users/destroy.html.erb, app/views/users/edit.html.erb, app/views/users/index.html.erb, app/views/users/new.html.erb, app/views/users/show.html.erb, app/views/users/update.html.erb, config/routes.rb, db/schema.rb, test/controllers/users_controller_test.rb
=> creating dashboard

Gemfile, Gemfile.lock, app/controllers/doctors_controller.rb, app/controllers/prescriptions_controller.rb, app/views/doctors/_form.html.erb, app/views/doctors/create.html.erb, app/views/doctors/destroy.html.erb, app/views/doctors/edit.html.erb, app/views/doctors/index.html.erb, app/views/doctors/new.html.erb, app/views/doctors/show.html.erb, app/views/doctors/update.html.erb, app/views/events/new.html.erb, app/views/prescriptions/_form-prescription.html.erb, app/views/prescriptions/create.html.erb, app/views/prescriptions/destroy.html.erb, app/views/prescriptions/edit.html.erb, app/views/prescriptions/index.html.erb, app/views/prescriptions/new.html.erb, app/views/prescriptions/show.html.erb, app/views/prescriptions/update.html.erb, config/routes.rb, db/migrate/20230614181106_add_first_name_to_doctors.rb, db/migrate/20230614181407_remove_name_from_doctors.rb, db/migrate/20230614222645_add_name_to_prescriptions.rb, db/schema.rb, db/seeds.rb, test/controllers/doctors_controller_test.rb, test/controllers/prescriptions_controller_test.rb
many changes to events, doctors and prescriptions controllers
=> Event and doctor controller work

app/controllers/prescriptions_controller.rb, app/models/doctor.rb, app/models/prescription.rb, app/views/events/new.html.erb, app/views/prescriptions/_form-prescription.html.erb, app/views/prescriptions/create.html.erb, app/views/prescriptions/edit.html.erb, app/views/prescriptions/index.html.erb, app/views/prescriptions/show.html.erb, config/routes.rb, db/schema.rb
finished controllers for events, doctors and prescriptions but views still are not done
=> finished controllers for events, doctors, prescriptions

app/assets/stylesheets/pages/index_task_page.scss, app/helpers/application_helper.rb, app/views/layouts/application.html.erb, app/views/tasks/_task_bar.html.erb, app/views/tasks/index.html.erb, db/schema.rb
updated the tasks view and html
=> updates to task_index html

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/home_index_page.scss, app/assets/stylesheets/pages/index_doctor_page.scss, app/controllers/doctors_controller.rb, app/models/doctor.rb, app/views/doctors/_form.html.erb, app/views/doctors/index.html.erb, app/views/pages/home.html.erb, app/views/posts/index.html.erb, app/views/tasks/index.html.erb, db/seeds.rb
Created the views for the doctors page, added some seeds for the prescriptions, and joined my code with Isaac's changes.
=> Doctors branch

Gemfile, Gemfile.lock, app/assets/stylesheets/pages/index_task_page.scss, app/controllers/tasks_controller.rb, app/helpers/application_helper.rb, app/javascript/application.js, app/views/tasks/_task_bar.html.erb, app/views/tasks/index.html.erb, app/views/tasks/new.html.erb
added more to tasks html index
=> added more to tasks html

app/controllers/events_controller.rb, app/views/events/_edit_event_modal.html.erb, app/views/events/_event-form.html.erb, app/views/events/_modal.html.erb, app/views/events/index.html.erb, app/views/simple_calendar/_calendar.html.erb
created modals for event creation and edit
=> Add event create button calendar

app/controllers/tasks_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/tasks_controller.js, app/views/tasks/_tasks.html.erb, app/views/tasks/index.html.erb
integrated the filter option for the tasks index
=> implemented tasks bar filtering

Gemfile, app/controllers/doctors_controller.rb, app/controllers/env_controller.rb, app/controllers/prescriptions_controller.rb, app/javascript/application.js, app/javascript/controllers/index.js, app/javascript/controllers/mapbox_controller.js, app/views/doctors/show.html.erb, app/views/layouts/application.html.erb, db/schema.rb, package.json, test/controllers/env_controller_test.rb, yarn.lock
added a mapbox to the doctor show page
a lot of things were dependent and added to various files including the mapbox library through yarn
=> Doctor show mapbox

Gemfile, Gemfile.lock, app/controllers/prescriptions_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/tabulator_controller.js, app/views/layouts/application.html.erb, app/views/prescriptions/_form-prescription.html.erb, app/views/prescriptions/index.html.erb, config/routes.rb, package.json, yarn.lock
added a prescription table for a prescription view
=> Prescription table

Gemfile, app/assets/stylesheets/components/_navbar.scss, app/views/pages/home.html.erb
Corrected some issues with the task view
=> solved the issues with the task index view

app/assets/stylesheets/pages/index_task_page.scss, app/controllers/tasks_controller.rb, app/helpers/application_helper.rb, app/javascript/controllers/index.js, app/javascript/controllers/tasks_controller.js, app/models/task_assigned_user.rb, app/models/user.rb, app/views/tasks/_task_bar.html.erb, app/views/tasks/_task_form.html.erb, app/views/tasks/index.html.erb, db/schema.rb
added to tasks and also added notifications
=> worked on tasks and notifications

Procfile.dev, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/home_index_page.scss, app/assets/stylesheets/pages/index_doctor_page.scss, app/controllers/doctors_controller.rb, app/javascript/application.js, app/javascript/controllers/index.js, app/javascript/controllers/multi_mapbox_controller.js, app/javascript/controllers/tasks_controller.js, app/models/doctor.rb, app/models/user.rb, app/views/doctors/index.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, config/environments/production.rb, db/schema.rb, db/seeds.rb, package.json, yarn.lock
=> Correct task branch

app/assets/stylesheets/pages/index_prescription_page.scss, app/javascript/controllers/prescription_form_controller.js
finshing the style touches to the API options
=> styled the prescription options

app/assets/stylesheets/pages/home_index_page.scss, app/assets/stylesheets/pages/index_doctor_page.scss, app/assets/stylesheets/pages/index_task_page.scss, app/javascript/controllers/tasks_controller.js, app/views/doctors/index.html.erb, app/views/pages/home.html.erb, app/views/tasks/index.html.erb, db/seeds.rb
=> more to html in tasks

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/index_task_page.scss, app/javascript/controllers/tasks_controller.js, app/views/tasks/index.html.erb
=> tasks manager html css

app/assets/stylesheets/pages/home_index_page.scss
Correct the issues with media queries.
=> corrected the issues with media queries

app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/pages/home_index_page.scss, app/assets/stylesheets/pages/index_event_page.scss, app/controllers/events_controller.rb, app/views/events/index.html.erb, app/views/pages/home.html.erb, app/views/tasks/index.html.erb, db/seeds.rb
finished dashboard and started events page
=> finished dashboard and started events page

app/assets/stylesheets/pages/index_doctor_page.scss, app/assets/stylesheets/pages/index_task_page.scss
=> fixing bugs

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/index_event_page.scss, app/assets/stylesheets/pages/index_prescriptions_page.scss, app/assets/stylesheets/pages/index_task_page.scss, app/controllers/prescriptions_controller.rb, app/controllers/tasks_controller.rb, app/helpers/application_helper.rb, app/models/prescription.rb, app/views/events/index.html.erb, app/views/prescriptions/index.html.erb, app/views/tasks/index.html.erb, config/routes.rb, db/seeds.rb
=> June29 isaac

app/assets/stylesheets/pages/index_post_page.scss, app/controllers/post_mentioned_users_controller.rb, app/controllers/posts_controller.rb, app/views/posts/index.html.erb
made some changes to paths after someone creates a post or mentions a user on a post
=> Jun29 lowell

app/assets/stylesheets/pages/index_doctor_page.scss, app/assets/stylesheets/pages/index_event_page.scss, app/assets/stylesheets/pages/index_post_page.scss, app/assets/stylesheets/pages/index_prescriptions_page.scss, app/controllers/doctors_controller.rb, app/views/doctors/_show.html.erb, app/views/doctors/index.html.erb, app/views/events/index.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/posts/index.html.erb, app/views/prescriptions/index.html.erb
more html and css to all pages
=> more html and css to all pages

app/javascript/controllers/tasks_controller.js, app/views/events/index.html.erb, app/views/layouts/application.html.erb, app/views/shared/_typedjs.html.erb, app/views/tasks/index.html.erb
=> Jun30 last min changes

Gemfile, Gemfile.lock, app/controllers/prescriptions_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/spinner_controller.js, app/models/user.rb, app/services/gpt_4_service.rb, app/views/prescriptions/index.html.erb, app/views/prescriptions/turbo_frames/_openai_recommendation.html.erb, config/application.rb, db/migrate/20230630202128_add_recommendation_to_prescriptions.rb, db/schema.rb
- Added service
- Turbo frame to avoid page reload
- Spinner animation controller
- OpenAI Configuration
- Recommendation and Prompt defilement
=> feat<openai>add openai service
